version: '3.1'

services: 
  localstack:
    image: localstack/localstack:latest
    environment: 
      - DEBUG=true
      - SERVICES=lambda,s3,cloudformation,sts,apigateway,iam,route53
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=local
      - HOST_TMP_FOLDER=${TMPDIR}
    ports: 
      - '4566-4597:4566-4597'
    volumes: 
      # - "/Users/clement/pocs/localstack-lambda-java:/Users/clement/pocs/localstack-lambda-java"
      - "$PWD:$PWD"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
